# Generated by Django 2.0.3 on 2018-04-15 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partograph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_type', models.CharField(blank=True, max_length=255, null=True)),
                ('caesarian', models.BooleanField(default=False)),
                ('cs_decision_time', models.DateTimeField(null=True)),
                ('initial_apgar', models.CharField(max_length=255, null=True)),
                ('live_birth', models.BooleanField(default=False)),
                ('newborn_weight_lbs', models.IntegerField(null=True)),
                ('newborn_weight_oz', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Practitioner')),
            ],
        ),
        migrations.CreateModel(
            name='PartoMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dilation_cm', models.SmallIntegerField()),
                ('descent', models.IntegerField()),
                ('station', models.CharField(max_length=255)),
                ('time_since_active_labor', models.DurationField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_taken', models.DateTimeField(auto_now_add=True)),
                ('partograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Partograph')),
            ],
        ),
    ]
