# Generated by Django 2.0.3 on 2018-04-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partograph',
            name='cs_decision_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='partograph',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partograph',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partograph',
            name='initial_apgar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partograph',
            name='newborn_weight_lbs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='partograph',
            name='newborn_weight_oz',
            field=models.IntegerField(null=True),
        ),
    ]