# Generated by Django 2.0.3 on 2018-04-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20180410_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partograph',
            name='caesarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partograph',
            name='live_birth',
            field=models.BooleanField(default=False),
        ),
    ]