# Generated by Django 2.0.3 on 2018-04-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_partograph_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partograph',
            name='delivery_type',
            field=models.IntegerField(choices=[(1, 'Vaginal Birth'), (2, 'Caesarian')], null=True),
        ),
    ]
