# Generated by Django 2.0.3 on 2018-04-17 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20180417_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='partomeasure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partomeasure',
            name='time_taken',
            field=models.DateTimeField(),
        ),
    ]
