FROM ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y \
    git \
    vim \
    python3 \
    python3-pip \
    python3-dev \
    nginx \
    supervisor \
    libpq-dev \
    postgresql \
    postgresql-contrib \
    pwgen && rm -rf /var/lib/apt/lists/*

# Base config, create django user and home
# RUN pip3 install uwsgi django

RUN mkdir /home/django

# Make the directories
RUN mkdir /src
RUN mkdir /config

# Pull the dependencies
ADD config/requirements.pip /config
# CMD ["/bin/bash",  "pip3 install -r /config/requirements.pip"]  # Need to be installed later

# nginx config
RUN echo "daemon off;" >> /etc/nginx/nginx.conf
COPY config/nginx/nginx-site.conf /etc/nginx/sites-available/default

# supervisor config
COPY config/supervisor.conf /etc/supervisor/conf.d/

# uWSGI config
COPY config/uwsgi.ini /home/django
COPY config/uwsgi_params /home/django

# Copy the src
COPY src /home/django/

# Copy initialization scripts
COPY config/init.sql /home/django
COPY config/start.sh /home/django

# CMD ["/bin/bash", "gunicorn /home/django/LaborTracker/LaborTracker.wsgi -b /home/django/website.sock"

EXPOSE 80
CMD ["/bin/bash", "/home/django/start.sh"]
